root = "."
tmp_dir = "tmp"

[build]
  bin = "/usr/bin/sleep infinity"
  full_bin = ""
  cmd = "templ generate && go build ./... && touch -m ../goravel-admin-demo/bootstrap/app.go"
  delay = 1000
  exclude_dir = ["tmp", ".git"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "jpg", "png", "css", "js"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
